# Generated by Django 3.0.5 on 2020-07-02 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tchr',
            old_name='mail',
            new_name='email',
        ),
        migrations.AlterModelTable(
            name='tchr',
            table='teacheregister',
        ),
    ]
