# Generated by Django 3.0.5 on 2020-07-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20200702_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='fileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
            ],
            options={
                'db_table': 'fileupload',
            },
        ),
    ]
