# Generated by Django 2.2.3 on 2020-07-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_fileupload10_fileupload11_fileupload12_fileupload3_fileupload4_fileupload5_fileupload6_fileupload7_f'),
    ]

    operations = [
        migrations.CreateModel(
            name='classupload1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload1',
            },
        ),
    ]
