# Generated by Django 2.2.3 on 2020-07-04 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_classupload1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classupload1',
            old_name='filename',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='classupload1',
            name='file',
        ),
    ]
