# Generated by Django 2.2.3 on 2020-07-04 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_auto_20200704_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='classupload1',
            name='file',
            field=models.FileField(default='', upload_to='files/pdfs/'),
        ),
    ]
