# Generated by Django 2.2.3 on 2020-07-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0009_auto_20200704_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='classupload10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload10',
            },
        ),
        migrations.CreateModel(
            name='classupload11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload11',
            },
        ),
        migrations.CreateModel(
            name='classupload12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload12',
            },
        ),
        migrations.CreateModel(
            name='classupload2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload2',
            },
        ),
        migrations.CreateModel(
            name='classupload3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload3',
            },
        ),
        migrations.CreateModel(
            name='classupload4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload4',
            },
        ),
        migrations.CreateModel(
            name='classupload5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload5',
            },
        ),
        migrations.CreateModel(
            name='classupload6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload6',
            },
        ),
        migrations.CreateModel(
            name='classupload7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload7',
            },
        ),
        migrations.CreateModel(
            name='classupload8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload8',
            },
        ),
        migrations.CreateModel(
            name='classupload9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files/pdfs/')),
                ('task', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'classupload9',
            },
        ),
    ]
