# Generated by Django 3.0.5 on 2020-07-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0010_classupload10_classupload11_classupload12_classupload2_classupload3_classupload4_classupload5_classu'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalscore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
                ('marks', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'finalscore',
            },
        ),
    ]
