# Generated by Django 3.0.5 on 2020-07-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0011_finalscore'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='finalscore',
            new_name='finalscoremodel',
        ),
    ]
