# Generated by Django 3.0.5 on 2020-07-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='mail',
            new_name='email',
        ),
    ]
