# Generated by Django 2.2.3 on 2020-07-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20200702_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='userssolution1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution1',
            },
        ),
    ]
