# Generated by Django 2.2.3 on 2020-07-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_userssolution1'),
    ]

    operations = [
        migrations.AddField(
            model_name='userssolution1',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userssolution1',
            name='week',
            field=models.CharField(default='', max_length=100),
        ),
    ]
