# Generated by Django 2.2.3 on 2020-07-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20200704_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='userssolution10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution10',
            },
        ),
        migrations.CreateModel(
            name='userssolution11',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution11',
            },
        ),
        migrations.CreateModel(
            name='userssolution12',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution12',
            },
        ),
        migrations.CreateModel(
            name='userssolution2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution2',
            },
        ),
        migrations.CreateModel(
            name='userssolution3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution3',
            },
        ),
        migrations.CreateModel(
            name='userssolution4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution4',
            },
        ),
        migrations.CreateModel(
            name='userssolution5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution5',
            },
        ),
        migrations.CreateModel(
            name='userssolution6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution6',
            },
        ),
        migrations.CreateModel(
            name='userssolution7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution7',
            },
        ),
        migrations.CreateModel(
            name='userssolution8',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution8',
            },
        ),
        migrations.CreateModel(
            name='userssolution9',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('task', models.CharField(max_length=100)),
                ('solution', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'userssolution9',
            },
        ),
    ]
